### ISSUE TITLE
Support unresolving a ticket

### ISSUE THREAD

**Issue by trickeydan** [trickeydan/helpdesk-system#4]
If a problem comes back, we should be able to mark the ticket as unresolved.

**Comment by PeterJCLaw** [comment]
Hrm, the use of a model for the resolution makes this a bit non-obvious how to represent. One approach might be to change the `TicketComment` mode into a `TicketEvent` model and store a status enum value on the `Ticket`. If we wanted status history that could also go on the `TicketEvent` as `new_status` & `old_status` fields.

**Comment by PeterJCLaw** [comment]
https://pypi.org/project/django-enumfield-ng/ is handy for enum fields if you want to be able to add extra things to the enum values later (which can be very powerful), though there are also implementations of a enumfields which use standard python enums (that one doesn't unfortunately).
